# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tile_data.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tile_data.proto',
  package='copicat.proto',
  syntax='proto3',
  serialized_pb=_b('\n\x0ftile_data.proto\x12\rcopicat.proto\"\x1c\n\x08TileData\x12\x10\n\x08raw_data\x18\x01 \x01(\x0c\x42\x0c\x42\nDataProtosb\x06proto3')
)




_TILEDATA = _descriptor.Descriptor(
  name='TileData',
  full_name='copicat.proto.TileData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='raw_data', full_name='copicat.proto.TileData.raw_data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=62,
)

DESCRIPTOR.message_types_by_name['TileData'] = _TILEDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TileData = _reflection.GeneratedProtocolMessageType('TileData', (_message.Message,), dict(
  DESCRIPTOR = _TILEDATA,
  __module__ = 'tile_data_pb2'
  # @@protoc_insertion_point(class_scope:copicat.proto.TileData)
  ))
_sym_db.RegisterMessage(TileData)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('B\nDataProtos'))
# @@protoc_insertion_point(module_scope)
